name: gitleaks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: |
          wget https://go.dev/dl/go1.18.1.linux-amd64.tar.gz
          tar -xzf go1.18.1.linux-amd64.tar.gz
          sudo mv go /usr/local/
          export PATH=$PATH:/usr/local/go/bin
          
      - name: install gitleaks
        run: |
          git clone https://github.com/zricethezav/gitleaks.git
          ls
          cd gitleaks
          ls
          make build
          cd ..
          
      - name: run gitleaks scan
        run: |
          gitleaks detect -s /
